# File extensions
PNG_FILE_EXTENSION = "png"
JPG_FILE_EXTENSION = "jpg"
JPEG_FILE_EXTENSION = "jpeg"
WEBP_FILE_EXTENSION = "webp"

# Allowed file list
ALLOWED_IMAGES_EXTENSIONS = (
    PNG_FILE_EXTENSION,
    JPG_FILE_EXTENSION,
    JPEG_FILE_EXTENSION,
    WEBP_FILE_EXTENSION,
)

MAX_TITLE_CHARACTERS_SIZE = 250
